imports_indent = "Visual"
imports_layout = "Vertical"
indent_style = "Block"
imports_granularity = "Preserve"
normalize_comments = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 10
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = false
type_punctuation_density = "Wide"
max_width = 200
remove_nested_parens = true
reorder_impl_items = true
